#common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        base64-secret: Mzg5ZTk5YTAzZmMxMTYzMzA4OTk0YzdlYmZmN2FmNDg0NDYzZTgwNmUxMTI0ZjhmN2RmOGJlNTg0MmM2MDNiYmFhNDUyNzJiZWRjYTY0MGI3ZTlkY2JjNmZjYzZjNzQzZTIxNg==
  logging:
    logstash: # forward logs to ELK
      enabled: false
      host: jhipster-logstash
  metrics:
    logs: # report metrics in the logs
      enabled: false
      report-frequency: 60 # in seconds

spring:
  zipkin:
    base-url: http://jhipster-zipkin:9411
    enabled: false
  sleuth:
    sampler:
      probability: 1 # report 100% of traces to Zipkin
eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@jhipster-registry:8761/eureka/
